use evdev::KeyCode;

use crate::machine_detect::ComputerModel;

pub type KeyLayout = &'static [&'static [(&'static str, KeyCode)]];

pub type KeyboardLayout = &'static [&'static [KeyLayout]];

const DATOR_BB_FÄLT_OLD_LAYOUT: KeyboardLayout = &[&[&[
    &[
        ("ESC", KeyCode::KEY_ESC),
        ("F1", KeyCode::KEY_F1),
        ("F2", KeyCode::KEY_F2),
        ("F3", KeyCode::KEY_F3),
        ("F4", KeyCode::KEY_F4),
        ("F5", KeyCode::KEY_F5),
        ("F6", KeyCode::KEY_F6),
        ("F7", KeyCode::KEY_F7),
        ("F8", KeyCode::KEY_F8),
        ("F9", KeyCode::KEY_F9),
        ("F10", KeyCode::KEY_F10),
        ("F11", KeyCode::KEY_F11),
        ("F12", KeyCode::KEY_F12),
        ("Prt Sc", KeyCode::KEY_SYSRQ),
        ("Scrl Lk", KeyCode::KEY_SCROLLLOCK),
        ("Pause", KeyCode::KEY_PAUSE),
    ],
    &[
        ("§", KeyCode::KEY_GRAVE),
        ("1", KeyCode::KEY_1),
        ("2", KeyCode::KEY_2),
        ("3", KeyCode::KEY_3),
        ("4", KeyCode::KEY_4),
        ("5", KeyCode::KEY_5),
        ("6", KeyCode::KEY_6),
        ("7", KeyCode::KEY_7),
        ("8", KeyCode::KEY_8),
        ("9", KeyCode::KEY_9),
        ("0", KeyCode::KEY_0),
        ("+", KeyCode::KEY_MINUS),
        ("`", KeyCode::KEY_EQUAL),
        ("Backspace", KeyCode::KEY_BACKSPACE),
        ("Home", KeyCode::KEY_HOME),
    ],
    &[
        ("Tab", KeyCode::KEY_TAB),
        ("Q", KeyCode::KEY_Q),
        ("W", KeyCode::KEY_W),
        ("E", KeyCode::KEY_E),
        ("R", KeyCode::KEY_R),
        ("T", KeyCode::KEY_T),
        ("Y", KeyCode::KEY_Y),
        ("U", KeyCode::KEY_U),
        ("I", KeyCode::KEY_I),
        ("O", KeyCode::KEY_O),
        ("P", KeyCode::KEY_P),
        ("Å", KeyCode::KEY_LEFTBRACE),
        ("^", KeyCode::KEY_RIGHTBRACE),
        ("'", KeyCode::KEY_BACKSLASH),
        ("PgUp", KeyCode::KEY_PAGEUP),
    ],
    &[
        ("CapsLock", KeyCode::KEY_CAPSLOCK),
        ("A", KeyCode::KEY_A),
        ("S", KeyCode::KEY_S),
        ("D", KeyCode::KEY_D),
        ("F", KeyCode::KEY_F),
        ("G", KeyCode::KEY_G),
        ("H", KeyCode::KEY_H),
        ("J", KeyCode::KEY_J),
        ("K", KeyCode::KEY_K),
        ("L", KeyCode::KEY_L),
        ("Ö", KeyCode::KEY_SEMICOLON),
        ("Ä", KeyCode::KEY_APOSTROPHE),
        ("Enter", KeyCode::KEY_ENTER),
        ("PgDn", KeyCode::KEY_PAGEDOWN),
    ],
    &[
        ("Shift", KeyCode::KEY_LEFTSHIFT),
        ("Z", KeyCode::KEY_Z),
        ("X", KeyCode::KEY_X),
        ("C", KeyCode::KEY_C),
        ("V", KeyCode::KEY_V),
        ("B", KeyCode::KEY_B),
        ("N", KeyCode::KEY_N),
        ("M", KeyCode::KEY_M),
        (",", KeyCode::KEY_COMMA),
        (".", KeyCode::KEY_DOT),
        ("-", KeyCode::KEY_SLASH),
        ("RShift", KeyCode::KEY_RIGHTSHIFT),
        ("↑", KeyCode::KEY_UP),
        ("End", KeyCode::KEY_END),
    ],
    &[
        ("LCtrl", KeyCode::KEY_LEFTCTRL),
        ("LWin", KeyCode::KEY_LEFTMETA),
        ("Alt", KeyCode::KEY_LEFTALT),
        ("<", KeyCode::KEY_102ND),
        ("Space", KeyCode::KEY_SPACE),
        ("AltGr", KeyCode::KEY_RIGHTALT),
        ("RCtrl", KeyCode::KEY_RIGHTCTRL),
        ("MENU", KeyCode::KEY_COMPOSE),
        ("Ins", KeyCode::KEY_INSERT),
        ("Del", KeyCode::KEY_DELETE),
        ("←", KeyCode::KEY_LEFT),
        ("↓", KeyCode::KEY_DOWN),
        ("→", KeyCode::KEY_RIGHT),
    ],
    &[
        ("MOUSE_LEFT", KeyCode::BTN_LEFT),
        ("MOUSE_RIGHT", KeyCode::BTN_RIGHT),
    ],
]]];

const DATOR_BB_FÄLT_NY_LAYOUT: KeyboardLayout = &[&[&[
    &[
        ("F1", KeyCode::KEY_F1),
        ("F2", KeyCode::KEY_F2),
        ("F3", KeyCode::KEY_F3),
        ("F4", KeyCode::KEY_F4),
        ("F5", KeyCode::KEY_F5),
        ("F6", KeyCode::KEY_F6),
        ("Sleep", KeyCode::KEY_SLEEP),
    ],
    &[
        ("`", KeyCode::KEY_GRAVE),
        ("1", KeyCode::KEY_1),
        ("2", KeyCode::KEY_2),
        ("3", KeyCode::KEY_3),
        ("4", KeyCode::KEY_4),
        ("5", KeyCode::KEY_5),
        ("6", KeyCode::KEY_6),
        ("7", KeyCode::KEY_7),
        ("8", KeyCode::KEY_8),
        ("9", KeyCode::KEY_9),
        ("0", KeyCode::KEY_0),
        ("+", KeyCode::KEY_MINUS),
        ("`", KeyCode::KEY_EQUAL),
        ("Backspace", KeyCode::KEY_BACKSPACE),
    ],
    &[
        ("Tab", KeyCode::KEY_TAB),
        ("Q", KeyCode::KEY_Q),
        ("W", KeyCode::KEY_W),
        ("E", KeyCode::KEY_E),
        ("R", KeyCode::KEY_R),
        ("T", KeyCode::KEY_T),
        ("Y", KeyCode::KEY_Y),
        ("U", KeyCode::KEY_U),
        ("I", KeyCode::KEY_I),
        ("O", KeyCode::KEY_O),
        ("P", KeyCode::KEY_P),
        ("Å", KeyCode::KEY_LEFTBRACE),
        ("^", KeyCode::KEY_RIGHTBRACE),
        ("'", KeyCode::KEY_BACKSLASH),
    ],
    &[
        ("CapsLock", KeyCode::KEY_CAPSLOCK),
        ("A", KeyCode::KEY_A),
        ("S", KeyCode::KEY_S),
        ("D", KeyCode::KEY_D),
        ("F", KeyCode::KEY_F),
        ("G", KeyCode::KEY_G),
        ("H", KeyCode::KEY_H),
        ("J", KeyCode::KEY_J),
        ("K", KeyCode::KEY_K),
        ("L", KeyCode::KEY_L),
        ("Ö", KeyCode::KEY_SEMICOLON),
        ("Ä", KeyCode::KEY_APOSTROPHE),
        ("Enter", KeyCode::KEY_ENTER),
    ],
    &[
        ("Shift", KeyCode::KEY_LEFTSHIFT),
        ("Z", KeyCode::KEY_Z),
        ("X", KeyCode::KEY_X),
        ("C", KeyCode::KEY_C),
        ("V", KeyCode::KEY_V),
        ("B", KeyCode::KEY_B),
        ("N", KeyCode::KEY_N),
        ("M", KeyCode::KEY_M),
        (",", KeyCode::KEY_COMMA),
        (".", KeyCode::KEY_DOT),
        ("-", KeyCode::KEY_SLASH),
        ("↑", KeyCode::KEY_UP),
        ("RShift", KeyCode::KEY_RIGHTSHIFT),
    ],
    &[
        ("LCtrl", KeyCode::KEY_LEFTCTRL),
        ("LWin", KeyCode::KEY_LEFTMETA),
        ("Alt", KeyCode::KEY_LEFTALT),
        ("<", KeyCode::KEY_102ND),
        ("Space", KeyCode::KEY_SPACE),
        ("MENU", KeyCode::KEY_COMPOSE),
        ("Del", KeyCode::KEY_DELETE),
        ("NumLk", KeyCode::KEY_NUMLOCK),
        ("←", KeyCode::KEY_LEFT),
        ("↓", KeyCode::KEY_DOWN),
        ("→", KeyCode::KEY_RIGHT),
    ],
    &[
        ("MOUSE_LEFT", KeyCode::BTN_LEFT),
        ("MOUSE_RIGHT", KeyCode::BTN_RIGHT),
    ],
]]];

const DATOR_BB_FÄLT_GPS: KeyboardLayout = &[&[&[
    &[
        ("Tab", KeyCode::KEY_TAB),
        ("Q", KeyCode::KEY_Q),
        ("W", KeyCode::KEY_W),
        ("E", KeyCode::KEY_E),
        ("R", KeyCode::KEY_R),
        ("T", KeyCode::KEY_T),
        ("Y", KeyCode::KEY_Y),
        ("U", KeyCode::KEY_U),
        ("I", KeyCode::KEY_I),
        ("O", KeyCode::KEY_O),
        ("P", KeyCode::KEY_P),
        ("+", KeyCode::KEY_MINUS),
        ("`", KeyCode::KEY_EQUAL),
        ("Å", KeyCode::KEY_LEFTBRACE),
        ("^", KeyCode::KEY_RIGHTBRACE),
        ("'", KeyCode::KEY_BACKSLASH),
        ("7", KeyCode::KEY_7),
        ("8", KeyCode::KEY_8),
        ("9", KeyCode::KEY_9),
        ("Del", KeyCode::KEY_DELETE),
    ],
    &[
        ("Shift", KeyCode::KEY_LEFTSHIFT),
        ("CapsLock", KeyCode::KEY_CAPSLOCK),
        ("A", KeyCode::KEY_A),
        ("S", KeyCode::KEY_S),
        ("D", KeyCode::KEY_D),
        ("F", KeyCode::KEY_F),
        ("G", KeyCode::KEY_G),
        ("H", KeyCode::KEY_H),
        ("J", KeyCode::KEY_J),
        ("K", KeyCode::KEY_K),
        ("L", KeyCode::KEY_L),
        (",", KeyCode::KEY_COMMA),
        (".", KeyCode::KEY_DOT),
        ("-", KeyCode::KEY_SLASH),
        ("↑", KeyCode::KEY_UP),
        ("Ö", KeyCode::KEY_SEMICOLON),
        ("Ä", KeyCode::KEY_APOSTROPHE),
        ("4", KeyCode::KEY_4),
        ("5", KeyCode::KEY_5),
        ("6", KeyCode::KEY_6),
        ("Enter", KeyCode::KEY_ENTER),
    ],
    &[
        ("LCtrl", KeyCode::KEY_LEFTCTRL),
        ("Alt", KeyCode::KEY_LEFTALT),
        ("LWin", KeyCode::KEY_LEFTMETA),
        ("Z", KeyCode::KEY_Z),
        ("X", KeyCode::KEY_X),
        ("C", KeyCode::KEY_C),
        ("V", KeyCode::KEY_V),
        ("B", KeyCode::KEY_B),
        ("N", KeyCode::KEY_N),
        ("M", KeyCode::KEY_M),
        ("Space", KeyCode::KEY_SPACE),
        ("<", KeyCode::KEY_102ND),
        ("←", KeyCode::KEY_LEFT),
        ("↓", KeyCode::KEY_DOWN),
        ("→", KeyCode::KEY_RIGHT),
        ("`", KeyCode::KEY_GRAVE),
        ("1", KeyCode::KEY_1),
        ("2", KeyCode::KEY_2),
        ("3", KeyCode::KEY_3),
        ("0", KeyCode::KEY_0),
    ],
]]];

const DEFAULT_MAIN_KEYBOARD_LAYOUT: KeyLayout = &[
    &[
        ("ESC", KeyCode::KEY_ESC),
        ("F1", KeyCode::KEY_F1),
        ("F2", KeyCode::KEY_F2),
        ("F3", KeyCode::KEY_F3),
        ("F4", KeyCode::KEY_F4),
        ("F5", KeyCode::KEY_F5),
        ("F6", KeyCode::KEY_F6),
        ("F7", KeyCode::KEY_F7),
        ("F8", KeyCode::KEY_F8),
        ("F9", KeyCode::KEY_F9),
        ("F10", KeyCode::KEY_F10),
        ("F11", KeyCode::KEY_F11),
        ("F12", KeyCode::KEY_F12),
    ],
    &[
        ("`", KeyCode::KEY_GRAVE),
        ("1", KeyCode::KEY_1),
        ("2", KeyCode::KEY_2),
        ("3", KeyCode::KEY_3),
        ("4", KeyCode::KEY_4),
        ("5", KeyCode::KEY_5),
        ("6", KeyCode::KEY_6),
        ("7", KeyCode::KEY_7),
        ("8", KeyCode::KEY_8),
        ("9", KeyCode::KEY_9),
        ("0", KeyCode::KEY_0),
        ("+", KeyCode::KEY_MINUS),
        ("`", KeyCode::KEY_EQUAL),
        ("Backspace", KeyCode::KEY_BACKSPACE),
    ],
    &[
        ("Tab", KeyCode::KEY_TAB),
        ("Q", KeyCode::KEY_Q),
        ("W", KeyCode::KEY_W),
        ("E", KeyCode::KEY_E),
        ("R", KeyCode::KEY_R),
        ("T", KeyCode::KEY_T),
        ("Y", KeyCode::KEY_Y),
        ("U", KeyCode::KEY_U),
        ("I", KeyCode::KEY_I),
        ("O", KeyCode::KEY_O),
        ("P", KeyCode::KEY_P),
        ("Å", KeyCode::KEY_LEFTBRACE),
        ("^", KeyCode::KEY_RIGHTBRACE),
        ("Enter", KeyCode::KEY_ENTER),
    ],
    &[
        ("CapsLock", KeyCode::KEY_CAPSLOCK),
        ("A", KeyCode::KEY_A),
        ("S", KeyCode::KEY_S),
        ("D", KeyCode::KEY_D),
        ("F", KeyCode::KEY_F),
        ("G", KeyCode::KEY_G),
        ("H", KeyCode::KEY_H),
        ("J", KeyCode::KEY_J),
        ("K", KeyCode::KEY_K),
        ("L", KeyCode::KEY_L),
        ("Ö", KeyCode::KEY_SEMICOLON),
        ("Ä", KeyCode::KEY_APOSTROPHE),
        ("'", KeyCode::KEY_BACKSLASH),
    ],
    &[
        ("Shift", KeyCode::KEY_LEFTSHIFT),
        ("<", KeyCode::KEY_102ND),
        ("Z", KeyCode::KEY_Z),
        ("X", KeyCode::KEY_X),
        ("C", KeyCode::KEY_C),
        ("V", KeyCode::KEY_V),
        ("B", KeyCode::KEY_B),
        ("N", KeyCode::KEY_N),
        ("M", KeyCode::KEY_M),
        (",", KeyCode::KEY_COMMA),
        (".", KeyCode::KEY_DOT),
        ("-", KeyCode::KEY_SLASH),
        ("RShift", KeyCode::KEY_RIGHTSHIFT),
    ],
    &[
        ("LCtrl", KeyCode::KEY_LEFTCTRL),
        ("LWin", KeyCode::KEY_LEFTMETA),
        ("Alt", KeyCode::KEY_LEFTALT),
        ("Space", KeyCode::KEY_SPACE),
        ("Alt Gr", KeyCode::KEY_RIGHTALT),
        ("RWin", KeyCode::KEY_RIGHTMETA),
        ("RCtrl", KeyCode::KEY_RIGHTCTRL),
    ],
];

const DEFAULT_SIDE_LAYOUT: KeyLayout = &[
    &[
        ("Insert", KeyCode::KEY_INSERT),
        ("Home", KeyCode::KEY_HOME),
        ("Page Up", KeyCode::KEY_PAGEUP),
    ],
    &[
        ("Delete", KeyCode::KEY_DELETE),
        ("End", KeyCode::KEY_END),
        ("Page Down", KeyCode::KEY_PAGEDOWN),
    ],
    &[("↑", KeyCode::KEY_UP)],
    &[
        ("←", KeyCode::KEY_LEFT),
        ("↓", KeyCode::KEY_DOWN),
        ("→", KeyCode::KEY_RIGHT),
    ],
    &[
        ("MOUSE_LEFT", KeyCode::BTN_LEFT),
        ("MOUSE_RIGHT", KeyCode::BTN_RIGHT),
    ],
];

const DEFAULT_NUMPAD_LAYOUT: KeyLayout = &[
    &[
        ("Num Lock", KeyCode::KEY_NUMLOCK),
        ("/", KeyCode::KEY_KPSLASH),
        ("*", KeyCode::KEY_KPASTERISK),
        ("-", KeyCode::KEY_KPMINUS),
    ],
    &[
        ("7", KeyCode::KEY_KP7),
        ("8", KeyCode::KEY_KP8),
        ("9", KeyCode::KEY_KP9),
        ("+", KeyCode::KEY_KPPLUS),
    ],
    &[
        ("4", KeyCode::KEY_KP4),
        ("5", KeyCode::KEY_KP5),
        ("6", KeyCode::KEY_KP6),
    ],
    &[
        ("1", KeyCode::KEY_KP1),
        ("2", KeyCode::KEY_KP2),
        ("3", KeyCode::KEY_KP3),
    ],
    &[
        ("0", KeyCode::KEY_KP0),
        (".", KeyCode::KEY_KPDOT),
        ("Enter", KeyCode::KEY_KPENTER),
    ],
];

const DEFAULT_KEYBOARD: KeyboardLayout = &[
    &[&DEFAULT_MAIN_KEYBOARD_LAYOUT],
    &[&DEFAULT_SIDE_LAYOUT, &DEFAULT_NUMPAD_LAYOUT],
];

// A list entry is (display name, layout)
pub const LAYOUT_OPTIONS: &[(&str, KeyboardLayout, Option<ComputerModel>)] = &[
    ("Default", DEFAULT_KEYBOARD, Some(ComputerModel::EjKänd)),
    (
        "Dator BB Fält — Ny",
        DATOR_BB_FÄLT_NY_LAYOUT,
        Some(ComputerModel::DatorBBFält),
    ),
    ("Dator BB Fält — Old", DATOR_BB_FÄLT_OLD_LAYOUT, None),
    (
        "Dator BB Fält GPS",
        DATOR_BB_FÄLT_GPS,
        Some(ComputerModel::DatorBBFältGPS),
    ),
];
